### ISSUE TITLE
Dependency conflict with current versions of dbt (protobuf)

### ISSUE THREAD

**Issue by atkinson** [gmyrianthous/dbt-airflow#155]
> `pip install dbt-core dbt-bigquery`
installed dbt-core=1.8.8 and dbt-bigquery=1.8.3 ok

> `pip install dbt-airflow`
Pip dependency resolver fails to resolve.

Using python 3.12.1 and pip 24.3.1 on Mac OS

**Comment by gmyrianthous** [comment]
Hey @atkinson, 

Thanks for reporting this. Will take a look and try to resolve it asap!

**Comment by atkinson** [comment]
thanks!

**Comment by DimitriSam** [comment]
Hi @atkinson, 

We’ve tried to replicate the issue using the latest versions of `dbt-core `and `dbt-bigquery` with Python 3.12, but we couldn’t reproduce it. Could you please provide  the full error log?

thanks

**Comment by atkinson** [comment]
Yes - it looks like it's been fixed since I reported it. Something upstream, I guess.
